# Entropy calculation 

## Definition of OD matrices

In [1]:
m1 <- matrix(c(1,2,0,1,1,1,2,0,1), nrow = 3, ncol = 3)
m2 <- matrix(c(2,1,0,1,1,1,1,1,1), nrow = 3, ncol = 3)
m3 <- matrix(c(2,1,0,1,2,0,1,0,2), nrow = 3, ncol = 3)

### Matrix m1

In [2]:
m1

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 2    1    0   
[3,] 0    1    1

### Matrix m2

In [3]:
m2

[,1] [,2] [,3]
[1,] 2    1    1   
[2,] 1    1    1   
[3,] 0    1    1

### Matrix m3

In [4]:
m3

[,1] [,2] [,3]
[1,] 2    1    1   
[2,] 1    2    0   
[3,] 0    0    2

## Function to calculate entropy

In [5]:
entropyCalculation <- function(m){
    
    #total trips in matrix
    trips_m <- sum(m)
    numerator <- factorial(trips_m)
    
    
    denominator <- 1
    
    for(i in 1:dim(m)[1]){
        
        for(j in 1:dim(m)[2]){
            
             denominator <- denominator*factorial(m[i,j])          
        }
    }
    
    entropym <- numerator/denominator
    
    return(entropym)
    
}

## Entropy matrix m1

In [6]:
print(paste("Entropy m1: ", entropyCalculation(m1)))

[1] "Entropy m1:  90720"


## Entropy matrix m2

In [7]:
print(paste("Entropy m2: ", entropyCalculation(m2)))

[1] "Entropy m2:  181440"


## Entropy matrix m3

In [8]:
print(paste("Entropy m3: ", entropyCalculation(m3)))

[1] "Entropy m3:  45360"
